
name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use xcconfig file
        env:
          XC_CONFIG_FILE: ${{ secrets.XC_CONFIG_FILE }}
        run: |
          echo "$XC_CONFIG_FILE" > config.xcconfig
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'fetch'
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'build'
