
name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - name: Use xcconfig file
        env:
          XC_CONFIG_FILE: ${{ secrets.XC_CONFIG_FILE }}
        run: |
          echo "$XC_CONFIG_FILE" > config.xcconfig
      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash
      - name: Tuist Fetch Dependency
        run: |
          tuist fetch && tuist generate
      - name: Tuist build
        run: | 
          tuist build
