
# workflow 의 이름
name: Run Test

on:
  push:
    branches: [ github-action-test ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test
        uses: actions/checkout@v3
      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash
      - name: Fetch Swift Packages
        run: tuist fetch
      - name: Build
        run: tuist build
      - name: Test
        run: tuist test
