name: deploy

on:
  push:
    branches: [ release/* , github-action-test]
jobs:
  deploy:
    runs-on: macos-latest
    env:
      # app archive 및 export 에 쓰일 환경 변수 설정
      XC_WORKSPACE: ${{ 'Lito.xcworkspace' }}
      XC_SCHEME: ${{ 'App' }}
      XC_ARCHIVE: ${{ 'Lito.xcarchive' }}
      
      # certification export key
      CERT_EXPORT_KEY: ${{ secrets.CERT_EXPORT_PWD }}
      KEYCHAIN: ${{ 'test.keychain' }}
      
      # Tuist signing
      ENCRYPTED_APP_DEBUG_MOBILEPROVISION_PATH: ${{ '.github/secrets/App.Debug.mobileprovision.gpg' }}
      ENCRYPTED_APP_RELEASE_MOBILEPROVISION_PATH: ${{ '.github/secrets/App.Release.mobileprovision.gpg' }}
      ENCRYPTED_LITO_CERT_PATH: ${{ '.github/secrets/Lito.cer.gpg' }}
      ENCRYPTED_LITO_P12_PATH: ${{ '.github/secrets/Lito.p12.gpg' }}
      DECRYPTED_APP_DEBUG_MOBILEPROVISION_PATH: ${{ 'Tuist/Signing/App.Debug.mobileprovision' }}
      DECRYPTED_APP_RELEASE_MOBILEPROVISION_PATH: ${{ 'Tuist/Signing/App.Release.mobileprovision' }}
      DECRYPTED_LITO_CERT_PATH: ${{ 'Tuist/Signing/Lito.cer' }}
      DECRYPTED_LITO_P12_PATH: ${{ 'Tuist/Signing/Lito.p12' }}
      
      CERT_SIGNING_KEY: ${{ secrets.CERTS_SIGNING_PWD }}
      
    steps:
      - name: Select latest Xcode
        # shell 이용해서 하나의 command 수행
        run: "sudo xcode-select -s /Applications/Xcode.app"
      - name: Checkout project
        # uses 키워드를 통해 Github Actions에서 기본으로 제공하는 액션을 사용 가능. 아래 액션은 repository 에 체크아웃하는 것
        uses: actions/checkout@v2
      - name: Configure Keychain 
        # 키체인 초기화 - 임시 키체인 생성
        run: |
          security create-keychain -p "" "$KEYCHAIN"
          security list-keychains -s "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security unlock-keychain -p "" "$KEYCHAIN"
          security set-keychain-settings
      - name : Tuist Signing
        run: |
          # Tuist Signing 파일들 복호화
          mkdir -p Tuist/Signing
          gpg -d -o "$DECRYPTED_APP_DEBUG_MOBILEPROVISION_PATH" --pinentry-mode=loopback --passphrase "$CERT_SIGNING_KEY" "$ENCRYPTED_APP_DEBUG_MOBILEPROVISION_PATH"
          gpg -d -o "$DECRYPTED_APP_RELEASE_MOBILEPROVISION_PATH" --pinentry-mode=loopback --passphrase "$CERT_SIGNING_KEY" "$ENCRYPTED_APP_RELEASE_MOBILEPROVISION_PATH"
          gpg -d -o "$DECRYPTED_LITO_CERT_PATH" --pinentry-mode=loopback --passphrase "$CERT_SIGNING_KEY" "$ENCRYPTED_LITO_CERT_PATH"
          gpg -d -o "$DECRYPTED_LITO_P12_PATH" --pinentry-mode=loopback --passphrase "$CERT_SIGNING_KEY" "$ENCRYPTED_LITO_P12_PATH"
          
      - name : Configure Code Signing
        run: |
          security import "$DECRYPTED_LITO_P12_PATH" -k "$KEYCHAIN" -P "" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN"
          
          # Xcode에서 찾을 수 있는 프로비저닝 프로필 설치하기 위해 우선 프로비저닝 디렉토리를 생성
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          # 디버깅 용 echo 명령어
          echo `ls Tuist/Signing/*.mobileprovision`
            # 모든 프로비저닝 프로파일을 rename 하고 위에서 만든 디렉토리로 복사하는 과정
            for PROVISION in `ls Tuist/Signing/*.mobileprovision`
            do
              UUID=`/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i ./$PROVISION)`
            cp "./$PROVISION" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
          done
      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash
      - name: Fetch Swift Packages
        run: tuist fetch
      - name: Use xcconfig file
        env:
          XC_CONFIG_FILE: ${{ secrets.XC_CONFIG_FILE }}
        run: |
          echo "$XC_CONFIG_FILE" > config.xcconfig
      - name: Generate
        run: tuist generate
      - name: Archive app
        # 빌드 및 아카이브
        run: |
          xcodebuild clean archive -workspace $XC_WORKSPACE -scheme $XC_SCHEME -configuration release -archivePath $XC_ARCHIVE
      - name: Export app
        # export 를 통해 ipa 파일 만듦
        run: |
          tuist export ipa -archivePath $XC_ARCHIVE -exportOptionsPlist ExportOptions.plist -exportPath . -allowProvisioningUpdates
      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'Lito.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
